default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cycle_depot_development
  port: 5433

test:
  <<: *default
  database: cycle_depot_test
  port: 5433

production:
  <<: *default
  database: cycle_depot_production
  username: cycle_depot
  password: <%= ENV['CYCLE_DEPOT_DATABASE_PASSWORD'] %>
